language: ruby
script:
- bundle exec bin/rails db:create
- bundle exec bin/rails db:migrate
- bundle exec rake
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: nP5wKQlXRrjjIM/hXwCvqkBYANvfo2kZSMLKNgx7NrNq1qYTSFKTwfVlhONvkfP3IAmPCPWlg0yvOk49SqXtccwyH3LyatJQ9XP+sN9mspiYr1TdMK5gOvAYnBakg3xNBUm2v6f6S/4YDp7dRGpjbK8tXyaUHbaS/AoAmHqQPUHGFMAXs/MXq4RiQT+i20r26nyt4qWGJbwvFbLdBd1V9q1bPew33Ada/vOoMum0Cm0HHon/JVtdnYeGrlIoCu5KEVN2hqbDqpZSqABo5UaKiWXtpGW5XXKAsgA7fnJv6l+EvMkMRwju/bC4B5wcE2xFJbNFiP40pb6LbwG+TSr0DwKiqR4+wy6xnIZbUlLAX+3fscBCeAj8HkfU1VAApYNyBy7sKADWISO5e/tOgB9DUUbwgdzkoIrH4CAGez4SW9F1rodXWw4p8Yf3tOWiLtyMJ+v+ILRGdvROT4RIz7x3K0kOnqysc6CKbR6kkHdKhSohbqnb2YyDBp0xaHW8r9OMmH8Ya7BvFeNkHdc+yDxxca1tVeSl/5qECvbhOO3pFTvxOMvBNCpp3DJGovwQ9P0hF8CoLdlbrxgZm1obijgu00Iv7LMn62OZr74nRnRYvHkukXeQ9F+fBMSGxib/tCh+/C4GjaA4qlN4AF/9LfVW9tMf92KicNDPyAADdUE3zAw=
  app: rocky-savannah-39650
  on:
    repo: chloeverity/acebook-breakfast-club
